### ISSUE TITLE
Semantic versioning recommends 0.1.0 as initial version

### ISSUE THREAD

**Issue by piratecarrot** [Mobject-Dev-Team/mobject-enumerable#1]
I am not sure if you are using the semantic versioning system, but if you are, the initial version number is recommended to be 0.1.0.
https://semver.org/

Currently the PLC project properties are set to 0.0.0.

> **How should I deal with revisions in the 0.y.z initial development phase?**
>The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

**Comment by benhar-dev** [comment]
Hi @piratecarrot, this has now been added to the coding style guide, and is now to be implemented on all future alpha repos.  Thank you for your input.
